version: '2'

services:
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ${DATA_SAVE_DIR}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
  web:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
    volumes:
      - ${VATUSA_SITE}:/var/www/vatusa
      - ${API_SITE}:/var/www/api
    links:
      - php
    depends_on:
      - php
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
  php:
    build:
      context: ./php
    volumes:
      - ${VATUSA_SITE}:/var/www/vatusa
      - ${API_SITE}:/var/www/api
    depends_on:
      - mysql

volumes:
  mysql:
    driver: "local"
