version: '2'

services:
  postgres:
    image: postgres:10.3-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPASSWORD=${POSTGRES_ROOT_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
  web:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
    volumes:
      - ${VATUSA_SITE}:/var/www/vatusa
      - ${API_SITE}:/var/www/api
    links:
      - php
    depends_on:
      - php
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
  php:
    build:
      context: ./php
    volumes:
      - ${VATUSA_SITE}:/var/www/vatusa
      - ${API_SITE}:/var/www/api
    depends_on:
      - postgres
